# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: InstallNuGetTools

- task: RestoreNugetPackages
  inputs:
    restoreSolution: '$(solution)'

- task: BuildSolution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: RunUnitTests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CreateNuGetPack-Beta
  inputs:
    command: 'pack' 
    packagesToPack: '**/MathEngine.Core/MathEngine.Core.beta.nuspec'
    configuration: '$(BuildConfiguration)'
    packDestination: '$(Build.ArtifactStagingDirectory)/NuGet-beta'

- task: CreateNuGetPack-Release
  inputs:
    command: 'pack' 
    packagesToPack: '**/MathEngine.Core/MathEngine.Core.nuspec'
    configuration: '$(BuildConfiguration)'
    packDestination: '$(Build.ArtifactStagingDirectory)/NuGet'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

